families = ["Tag16H5"]
network_table_addr = "169.254.110.127"
network_table_port = 5810
[cli]
shapening = 8.0
decimation = 8.0

rmin = 100
rmax = 200

gmin = 220
gmax = 255

bmin = 150
bmax = 220

aspect_min = 3.2
aspect_max = 5.0