families = ["Tag16H5"]
network_table_addr = "172.22.11.2"
network_table_port = 5810
[cli]
shapening = 6.0
decimation = 6.0

rmin = 100
rmax = 200

gmin = 220
gmax = 255

bmin = 150
bmax = 220

aspect_min = 3.2
aspect_max = 5.0