[target.aarch64-unknown-linux-gnu]
linker="/home/t-linux/toolchain/bin/aarch64-buildroot-linux-gnu-gcc"
rustflags=[
    "-C", "link-arg=--sysroot=/home/t-linux/toolchain/aarch64-buildroot-linux-gnu/sysroot",
]